title: 			JSM85
description: 	'Blogging from the London Underground!'
blog_url: 		http://jsm85.github.io

author:
  name: 		'Joe Mendonca'
  email: 		jsmendonca@gmail.com
  github_id: 	jsm85
  twitter_id: 	JSMendonca85
  linkedin_id: 	jsm85

safe: 			true
timezone: 		Europe/London


markdown: 		kramdown
permalink: pretty


prose:
  rooturl: 		'_posts'
  media:		'assets'

google_analytics_tracking_id: UA-39754237-1